FROM node:14-alpine3.14 as builder

COPY package.json  ./

RUN yarn install 

RUN mkdir /profile

RUN mv ./node_modules ./profile

WORKDIR /profile

COPY . .

RUN yarn run ng build --prod --project=profile

RUN ls projects/profile

FROM nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /profile/dist/profile /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
